### ISSUE TITLE
Github action "YunoHost apps package linter" is failing

### ISSUE THREAD

**Issue by ewilly** [YunoHost/package_linter#107]
Starting from the 28/11/2022, the cron test failed with the above result :
`Run ~/package_linter/package_linter.py .
Traceback (most recent call last):
  File "/home/runner/package_linter/package_linter.py", line 4, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
Error: Process completed with exit code 1.`
See for example : [https://github.com/YunoHost-Apps/homeassistant_ynh/actions/runs/3572177335/jobs/6004771915](https://github.com/YunoHost-Apps/homeassistant_ynh/actions/runs/3572177335/jobs/6004771915)

**Comment by jedie** [comment]
Yes, see it also: https://github.com/YunoHost-Apps/django_example_ynh/actions/runs/3752086868/jobs/6373846938

Bugfix: Just add `pip3 install toml` to pipeline, see: https://github.com/YunoHost-Apps/django_example_ynh/pull/33/commits/69d8c640793088267206c83adcf67e675f88ed6b

**Comment by alexAubin** [comment]
Somewhat fixed in https://github.com/YunoHost/package_linter/commit/bd6ad626d9a343b665bad1bc19e671fc54255c52
