### ISSUE TITLE
url field without upstream

### ISSUE THREAD

**Issue by selfhoster1312** [YunoHost/package_linter#108]
I am making a package that only uses preinstalled packages (nginx). If i don't set `url` field in manifest.json, i get error `The following mandatory fields are missing: ['url']`. If i set it to the package's repo, i get warning (or info?) `'url' is not meant to be the URL of the YunoHost package, but rather the website or repo of the upstream app itself...`.

If i remove the `upstream` section, i also get:

```
You are encouraged to add an 'upstream' section in the manifest, filled with the website, demo, repo, license of the upstream app, as shown here: https://github.com/YunoHost/example_ynh/blob/7b72b7334964b504e8c901637c73ce908204d38b/manifest.json#L11-L18 . (Not all infos are mandatory, you can remove irrelevant entries)
```

It's not clear to me what i should do in this case.

**Comment by alexAubin** [comment]
What does your app installs exactly ? Isnt there anything that could be considered to be the upstream ?

**Comment by selfhoster1312** [comment]
The app installs nothing. It just configures a reverse proxy in nginx config. I considered making pull request to redirect_ynh, but:

- it was the occasion for me to be more familiar with yunohost app packaging 
- i'm not sure redirect_ynh wants to cobble the settings interface with reverse proxy specific settings

The difference with redirect_ynh reverse proxy is:

- i set up 302 redirect from APPPATH to APPPATH/
- i add a setting for serving static assets folder from nginx (more optimized, and can add caching settings in the future)

**Comment by alexAubin** [comment]
Hmyeah special apps like this dont really fit into the url or upstream that much, that's not really a big deal

Naively I would just add like a link to the wikipedia page about reverse proxy or something like this, both in the `url` and `upstream` -> `website`

**Comment by selfhoster1312** [comment]
> Naively I would just add like a link to the wikipedia page about reverse proxy

I will do that thanks.

I think there is value in supporting apps without upstream for custom configs which don't install packages, but if you don't agree feel free to close this issue.

**Comment by alexAubin** [comment]
Yes they are supported, it's just needed to define some sort of upstream url even if there's no actual upstream ... I mean even the message `'url' is not meant to be the URL of the YunoHost package` is only an info and not a warning precisely because some special apps (such as redirect_ynh) do not have actual upstream (though ideally we should replace the `url` value with something else than just the git repo of the app)
