### ISSUE TITLE
Licence plus seulement à free ou non-free

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/package_linter#16]
Suite à la validation de la YEP sur la licence
https://github.com/YunoHost/doc/blob/master/packaging_apps_guidelines_fr.md#yep-13---indiquer-la-licence-associ%C3%A9e-au-paquet---brouillon--auto--working-

La licence ne doit plus se limiter seulement à free/non-free, en l'état package linter indique une erreur.

**Comment by M5oul** [comment]
License field could be checked with an SPDF field linter as [tools on python packages](https://pypi.python.org/pypi?%3Aaction=search&term=spdx&submit=search).

**Comment by alexAubin** [comment]
Fixed here https://github.com/YunoHost/package_linter/commit/8c70d51c6b939c80117ce55cec4d2d7fd9a00a3b#diff-2cb3a7966fcf81dc02ba8722d74be525R188
