### ISSUE TITLE
False positive? 'utf-8' codec can't decode byte 0x80 in position 99: invalid start byte 

### ISSUE THREAD

**Issue by Krakinou** [YunoHost/package_linter#166]
https://ci-apps-bullseye-dev.yunohost.org/ci/job/20793

**Comment by Salamandar** [comment]
Yeah, the linter expects "config" files to be pure text, not binary… so of course when trying to decode with utf-8, it breaks.

**Comment by Krakinou** [comment]
make sense.
Should move in /sources?

**Comment by Salamandar** [comment]
No, we just fixed our linter to ignore files that do not look like ascii/unicode files.
