### ISSUE TITLE
Use Shellcheck?

### ISSUE THREAD

**Issue by M5oul** [YunoHost/package_linter#24]
https://github.com/koalaman/shellcheck

**Comment by M5oul** [comment]
https://hackaday.com/2017/03/29/lint-for-shell-scripters/

**Comment by Jibec** [comment]
Using shellcheck is a good idea, I personally use it online: https://www.shellcheck.net/
I'm unsure this should be inside the result of package_linter itself, but more as a distinct test result (it can talk a lot).

We also have to fix our errors in YunoHost's helpers.

**Comment by Mickael-Martin** [comment]
shellcheck exists as package : 
`apt install shellcheck`

**Comment by alexAubin** [comment]
Closing because hmpf, I'm not convinced we really need this, we should rather spend energy on switching to a declarative app format..
