### ISSUE TITLE
Enforce id naming rules

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost/package_linter#28]
We could check the id against the right regexp as stated in [YEP 1.1](https://github.com/YunoHost/doc/blob/master/packaging_apps_guidelines_fr.md#yep-11---nommer-son-app-et-son-d%C3%A9p%C3%B4t---valid%C3%A9--manuel--notworking-).

**Comment by alexAubin** [comment]
Current code already implements this :+1:
