### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by M5oul** [YunoHost/package_linter#3]
- [x] add `ynh_die` check.
- [ ] add non use of helpers check.
- [ ] add check of `rm -rf /var/www/${app}` in `remove` script:
 - if `$app` is unset it could remove `/var/www`.
 - `set -u` can't be used on remove script as it will stop the script at this error.
 - [solution](https://github.com/YunoHost-Apps/gogs_webhost_ynh/blob/master/scripts/remove#L11)
- [ ] add comments to explain how works the code.
- [ ] split code in specialized files (script, manifest…etc)

**Comment by alexAubin** [comment]
I think it's basically done nowadays ...
