### ISSUE TITLE
ynh_abort_if_errors warning: the URL is a 404

### ISSUE THREAD

**Issue by kemenaran** [YunoHost/package_linter#32]
The link provided with the `ynh_abort_if_errors` error message points to a 404 destination.

https://github.com/YunoHost/package_linter/blob/76cef0657660ae9cbba467db80459213b1b46f53/package_linter.py#L336-L337

What would the correct link be?

**Comment by liberodark** [comment]
not work this link not work

**Comment by alexAubin** [comment]
Fixed in 247c78c
