### ISSUE TITLE
False error "ynh_abort_if_errors is missing"

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/package_linter#36]
Sometimes, Package linter says "ynh_abort_if_errors is missing." even if ynh_abort_if_errors is in the script.

See [here](https://ci-apps.yunohost.org/jenkins/job/jenkins%20(Community)/lastBuild/consoleFull) and [here](https://github.com/YunoHost-Apps/jenkins_ynh/blob/master/scripts/upgrade#L66) for example.

**Comment by alexAubin** [comment]
I believe this is due to the library we use, shlex, to have completely fucked up behaviors. Should be fixed by https://github.com/YunoHost/package_linter/pull/43

**Comment by alexAubin** [comment]
Closing the issue because i'll forget later :|
