### ISSUE TITLE
Sometimes bugs on linter ?

### ISSUE THREAD

**Issue by aymhce** [YunoHost/package_linter#37]
I think there is sometimes bugs on linter. You can see here (linter part) https://ci-apps.yunohost.org/jenkins/job/portainer%20(Community)/6/consoleFull

And sadly, my app was downgrade from level 7 to 3 for that :'( I think it's strange.

Thanks

**Comment by alexAubin** [comment]
Sorry, do you have another working link for this ? Or do you recall what it was ? Was it false-negative / false-positives, or was it a total crash with a stacktrace ?

**Comment by alexAubin** [comment]
You can connect to  https://ci-apps.yunohost.org/ci/. But  https://ci-apps.yunohost.org/jenkins/job/portainer%20(Community)/6/consoleFull won't work anymore because we moved away from jenkins half a year ago :S

**Comment by aymhce** [comment]
Ok, thanks, as there is nothing left in connection with the ticket, I close it.
