### ISSUE TITLE
Quelques régressions

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost/package_linter#4]
Je viens de faire un test de nextcloud, en attente de validation. Je vais voir pour faire une PR sur ce package, car il y a quelques erreurs.

Mais il y a des faux positifs avec Package linter.

- Pour exemple, sur le script install, Package linter indique "you should add "sudo" before this command line" sur les [lignes 152 à 155](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/install#L152-L155). Or ces lignes sont bien préfixée par sudo.

On retrouve cette erreur aux [lignes 221 à 224](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/upgrade#L221-L224) du script upgrade et [70 à 73](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/restore#L70-L73) du script restore.

- Package linter indique également "'ynh_die' or 'exit' command is executed with system modification before." aux lignes [120 du script install](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/install#L120) et [176 du script upgrade](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/upgrade#L176).
Mais dans les 2 cas, ce sont des commandes essentielles exécutée via owncloud, ce qui implique donc qu'il a été installé préalablement. Et donc modification système.
Dans la mesure où un échec de ces commandes provoquera une sortie en erreur, le script remove devrait être exécuté. Donc une modification du système devrait être nettoyée par le script remove.

- Enfin, sur le fichier de fonctions additionnel. On trouve l'erreur relative à sudo sur les lignes [34](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/_common.sh#L34), [41](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/_common.sh#L41) et [109](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/_common.sh#L109). Or dans ces 3 cas, les fichiers n'appartiennent pas à root, mais à admin, donc sudo n'est pas nécessaire.
Cela étant, dissocier ces situations me semble pas évident via un script...

- Et à la ligne [47](https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/_common.sh#L47), à nouveau une erreur ynh_die sur une commande qui implique nécessairement des modifications préalable.
Toutefois, je me pose la question du check des ynh_die et exit sur les fonctions, as-tu limité le champs d'analyse aux fonctions ou à l'ensemble du fichier? Le script n'étant, ici, pas linéaire.

**Comment by M5oul** [comment]
Il y a tellement d’exceptions possibles à gérer.
Ça ne m’intéresse pas de toutes les gérer.
C’est à l’utilisateur de package_linter d’avoir un regard critique sur les résultats du linter.
Le linter est surtout là pour détecter des points critiques non détectés visuellement.

En effet, tu soulèves des points importants à traiter.
J’ai ajouté la vérification des fichiers de fonctions, et en effet, certaines vérifications sur ces derniers n’ont pas lieu d’être.

**Comment by maniackcrudelis** [comment]
Ça rejoint ce que je te disais sur le salon.
Ce serait pas mal de dissocier des erreurs et des warnings

Pour éviter que le CI ne pose des erreurs partout si c'est juste des petits détails.

**Comment by M5oul** [comment]
Linked to https://github.com/YunoHost/package_linter/issues/7.

**Comment by M5oul** [comment]
May also be spammed but now the return value is no more set.
It shall pass tests.
