### ISSUE TITLE
ynh_exec_as: command not found

### ISSUE THREAD

**Issue by yalh76** [YunoHost/package_linter#44]
New version of package_linter advise:

 [YEP-2.12] You should not need to use 'sudo', the script is being run as root. (If you need to run a command using a specific user, use 'ynh_exec_as')

But ynh_exec_as is not included in the default helpers: https://yunohost.org/#/packaging_apps_helpers_en
Still in the experimental helpers ...

**Comment by alexAubin** [comment]
:sweat_smile:

**Comment by alexAubin** [comment]
Package linter doesn't warn anymore if you "sudo -u someuser"
