### ISSUE TITLE
Warn if yunohost requirement in manifest is lower than current YunoHost version ?

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/package_linter#48]
I suspect many maintainer might not remember to update the version requirement in manifest.json ? We could try to warn if the maintainer if the version is significanty lower compared to yunohost current version ... (e.g. requirement says 3.2 but yunohost current version is 3.4)

Dunno if that's relevant, we could also consider that users should keep their install up to date :/

**Comment by Mickael-Martin** [comment]
For me this is make sense. Do you want a PR  ?

**Comment by alexAubin** [comment]
PR got merged
