### ISSUE TITLE
Check source common.sh in restore file

### ISSUE THREAD

**Issue by kay0u** [YunoHost/package_linter#50]
Package_linter should display an error when a `source _common.sh` is done instead of `source ../settings/scripts/_common.sh` in the restore file.

**Comment by maniackcrudelis** [comment]
If you source _common.sh in a restore script, it's probably going to fail anyway.

**Comment by kay0u** [comment]
Yes, but with a nice message, we could help people top fix this issue

**Comment by Mickael-Martin** [comment]
I will try

**Comment by alexAubin** [comment]
PR got merged
