### ISSUE TITLE
Manifest tests proposal

### ISSUE THREAD

**Issue by Jibec** [YunoHost/package_linter#53]
here a some ideas of basics tests:

- detect empty values: https://github.com/beudbeud/proftpd_ynh/blob/941de133317c82a3c2a0fada2e4331f4c233e0f6/manifest.json#L5 (https://github.com/YunoHost/issues/issues/888)
- detect double "en" values, https://github.com/YunoHost-Apps/chtickynotes_ynh/commit/94575a0db73e0ba1028882c625ebb363b0450f01 (https://github.com/YunoHost/issues/issues/887)

**Comment by alexAubin** [comment]
PR got merged

**Comment by Jibec** [comment]
thank you Alex
I think we should start to have tests for this linter ;)
