### ISSUE TITLE
Add checks for old methods and propose helpers

### ISSUE THREAD

**Issue by M5oul** [YunoHost/package_linter#6]
##### User exist
- ? –> `ynh_user_exists`

##### Database
- `dd if=/dev/urandom`, `openssl rand`? –> `ynh_string_random`
- `mysql`, `yunohost app initdb` ? –> `ynh_mysql_create_db`

##### No helpers
- `checkurl`, `ssowatconf`, `addaccess` there isn't helpers for those cmds

**Comment by alexAubin** [comment]
Done in https://github.com/YunoHost/package_linter/pull/43/commits/f31bebc644b08f25b3f5d67209eec41449dd2df8
