### ISSUE TITLE
Warnings in "[Loading App]"

### ISSUE THREAD

**Issue by Jibec** [YunoHost/package_linter#65]
Hello,
I have these warnings:
>  [Loading App]
> 
> ! /home/jb//package_check/weblate_ynh_check/scripts/install : Could not parse this line (No closing quotation) : message=" 
> ! /home/jb//package_check/weblate_ynh_check/scripts/install : Could not parse this line (No closing quotation) : " 
> ! /home/jb//package_check/weblate_ynh_check/scripts/upgrade : Could not parse this line (No closing quotation) : mail_message=" 
> ! /home/jb//package_check/weblate_ynh_check/scripts/upgrade : Could not parse this line (No closing quotation) : " 

It comes from: https://github.com/YunoHost-Apps/weblate_ynh/blob/master/scripts/install#L314

I assume the bash script is correct, as http://shellcheck.net doesn't say anything. What do you think?

**Comment by alexAubin** [comment]
>I assume the bash script is correct, as http://shellcheck.net doesn't say anything. What do you think?

Yes, your script is okay. It's mainly due to the way we parse the script file, which is now done line-by-line, and therefore kinda incompatible with multi-line statements ...

Still trying to think how to handle this without scaring app maintainers so much

**Comment by Mickael-Martin** [comment]
Same thing for me :
>
>[Loading App]
> 
> ! zabbix_ynh/scripts/install : Could not parse this line (No closing quotation) : echo "<?php 
> ! zabbix_ynh/scripts/install : Could not parse this line (No closing quotation) : \$IMAGE_FORMAT_DEFAULT = IMAGE_FORMAT_PNG;">/usr/share/zabbix/conf/zabbix.conf.php

**Comment by alexAubin** [comment]
Closing because sortof fixed it a while ago: it's now not a real warning anymore + there's a message to say it's probably ok
