### ISSUE TITLE
Yep if script find sudo word

### ISSUE THREAD

**Issue by Mickael-Martin** [YunoHost/package_linter#67]
Hi,

```
if self.contains("sudo"):
            print_warning(
                "[YEP-2.12] You should not need to use 'sudo', the script is being run as root. "
                "(If you need to run a command using a specific user, use 'ynh_exec_as')"
)
```
Match if I use sudoers directory for example. Sorry I have no time to purpose a patch this time.

**Comment by kay0u** [comment]
A simple:
`if self.contains("sudo "):` should do the trick? But it's ugly.

**Comment by Mickael-Martin** [comment]
Yes. It works for me ! But too ugly ? (I don't know)

**Comment by alexAubin** [comment]
Imho that's good enough ¯\\\_(ツ)\_/¯
