### ISSUE TITLE
YEP-3.7 error

### ISSUE THREAD

**Issue by yalh76** [YunoHost/package_linter#71]
When copying the experimental helper ynh_add_extra_apt_repos__3 into _common.sh there is a package_linter error
`[YEP-3.7] Manually messing with apt's sources.lists is strongly discouraged and should be avoided. Please consider alternatives like using a .deb directly or using experimental helpers (c.f. https://github.com/YunoHost-Apps/Experimental_helpers/tree/master/ynh_add_secure_repos ) `

because in experimental helper ynh_add_extra_apt_repos__3 there is `/etc/apt/sources.list` in the helper.

Does this mean that is better not to copy paste experimental helper content in _common.sh or package linter need to be corrected ?

**Comment by kay0u** [comment]
I think it's more a big from the linter introduced here:
https://github.com/YunoHost/package_linter/pull/70

An easy way to avoid this detection is to copy paste the helper to another file (like `_experimental.sh` for example), and source it in the `_common.sh`.

But PR would be awesome too ;-)

**Comment by yalh76** [comment]
> _experimental.

I use to copy the experimental helper file and add `source ynh_add_extra_apt_repos__3` at the beginning (best way for me to manage and update experimental helpers) but for some package that I'm not directly the maintainer, the maintainer prefer to copy paste the content of the experimental helper in `_common.sh` ...

I think I will do a PR on #70 saying : if there is `/etc/apt/sources.list` in `_common.sh` but not `ynh_add_repo` then [YEP-3.7] error (that will improve my python skills ^^ and took me hours ^^)

**Comment by yalh76** [comment]
Done and tested on https://github.com/YunoHost/package_linter/pull/73

If validated and merged, several apps will increase from level 4 to level 7 ^^ and we love level 7 apps.

**Comment by kay0u** [comment]
> [...] and we love level 7 apps.

Ho yeah!
