### ISSUE TITLE
Warning for ssowatconf

### ISSUE THREAD

**Issue by kay0u** [YunoHost/package_linter#74]
https://github.com/YunoHost/package_linter/blob/bd8414ed6e8e83bc72a71191be00f57ec2029ce1/package_linter.py#L581-L582

Sometimes, we want to use `yunohost app ssowatconf`:

https://github.com/YunoHost/example_ynh/blob/998554426865d726f91b3be23d6f56fd52d2b0ed/scripts/install#L221

I know, it's just a warning, but I don't like the yellow on my linter :100: 

(Close it if you think this issue is useless)

**Comment by alexAubin** [comment]
Ah yes indeed

Hmm maybe we could find some trick to check that this line is near the end of the script (usually the case for old apps)

**Comment by alexAubin** [comment]
Should be better with new version (only check ssowat near the end of file)
