### ISSUE TITLE
Enhance manifest check

### ISSUE THREAD

**Issue by M5oul** [YunoHost/package_linter#8]
##### JsonSchema
use `jsonchema` to check the manifest, with works done by ju:
- https://github.com/YunoHost/yunotest/blob/master/apps_tests/manifest_schema.json
- https://github.com/YunoHost/yunotest/blob/master/apps_tests/__init__.py

##### Hardcore way
Check under arrays:
```python
manifest["description"]["en"]
manifest["maintainer"]["name"]
manifest["maintainer"]["email"]
manifest["arguments"]["install"]
```

**Comment by alexAubin** [comment]
Closing because the current code is good enough
