### ISSUE TITLE
Nginx checks

### ISSUE THREAD

**Issue by M5oul** [YunoHost/package_linter#9]
If Nginx is on the manifest, check:
- `/conf/nginx.conf` file is here.
- `sudo service reload nginx` inside `install`, `remove`, `upgrade` and `restore` shell scripts (`backup` don't needs it)

**Comment by Jibec** [comment]
I also suggest to serch for __PATH__/
Path should not be followed by a slash

**Comment by alexAubin** [comment]
Closing, old issue, pretty much implemented
