### ISSUE TITLE
Error when remove old entry in conf.json.persistent

### ISSUE THREAD

**Issue by Josue-T** [YunoHost/package_linter#93]
Hello,

I'm working to remove some old entry in the file `/etc/ssowat/conf.json.persistent`. So I made script which remove old entry which was no more needed. But I still get this error on the liner !!!
```
✘ Don't do black magic with /etc/ssowat/conf.json.persistent !
```

**Comment by alexAubin** [comment]
Uh wokay but what does your script do exacly ?

Basically the linter greps line containing /etc/ssowat/conf.json.persistent ... : https://github.com/YunoHost/package_linter/blob/master/package_linter.py#L581

**Comment by Josue-T** [comment]
Thanks for your response:

By example: https://github.com/YunoHost-Apps/sogo_ynh/blob/permissions/scripts/remove_sso_conf_persistent.py

**Comment by alexAubin** [comment]
So if I understand correctly the point is to cleanup the old legacy stuff and therefore that's a legit use case ?

I guess in that case you could trick the linter by creating a var like `persistent_file = '/etc/ssowat/' + 'conf.json.persistent'` such that grep doesn't find it :/

**Comment by Josue-T** [comment]
OK, will do this, thanks

**Comment by alexAubin** [comment]
Closing, assuming it's fixed
